Category icons and tooltip
endlessm/godot-block-coding pull request #270
Opened 2024-10-13 05:14 UTC by DoomTas3r

Shortens categories and gives them icons and tooltips. I couldn't find the Gnome icons so I edited and used the Godot icons. Loading the icons was not optimized and the icons look like they were upscaled. The log icon is hard to see on dark themes

Same as the idea https://github.com/endlessm/godot-block-coding/issues/131#issuecomment-2253548713

- Check for changes that might break code

![image](https://github.com/user-attachments/assets/d6d3e26a-cbac-4014-9e44-3a8beb5fe69c)

2024-10-17 23:45 UTC, DoomTas3r commented
I think I understand how squash works now. I will squash the commits in other pull requests

2025-01-30 19:07 UTC, cassidyjames commented
On HiDPI (2× scaling) the icons look tiny; is there a way to make them scale with the UI? 
![image](https://github.com/user-attachments/assets/762123f4-c98e-47f6-9ceb-7db95a4fa042)

2025-01-31 01:45 UTC, DoomTas3r commented
@cassidyjames I changed the import files so that the icons scale with the editor. How do they look now?

2025-02-03 15:22 UTC, manuq commented
@DoomTas3r this is looking very nice! By the way, I don't have an HiDPI display.
![Captura desde 2025-02-03 12-20-20](https://github.com/user-attachments/assets/f217fafb-f03d-45a8-83bb-5799933f80b3)

2025-02-04 23:05 UTC, cassidyjames approved these changes
UI-wise this looks and feels great to me. Nice work

![image](https://github.com/user-attachments/assets/86f7954c-0845-4afd-9b6f-cf72201b2d81)


I've confirmed the icons now scale correctly on HiDPI. I was going to point out that it looks like the category labels don't scale, but they don't in main, either…

![image](https://github.com/user-attachments/assets/000548e0-89fa-4bea-8b29-e1641543ce11)

I'll file a separate issue for that. :)

2025-02-05 10:14 UTC, manuq commented
@DoomTas3r would you like to cleanup the PR? The second commit undo things done by the first one. For example I see icons added and then removed. So you should squash them into one and provide a descriptive commit message. Then we can start reviewing!

2025-02-05 10:24 UTC, manuq requested changes

2025-02-05 10:24 UTC, manuq commented on addons/block_code/ui/constants.gd
> +		"icon": "lifecycle",
Below in the PR you do this for the button tooltip text:
```
_button.tooltip_text = tr(category.name.get_slice(" |", 0))
```

So I think it's better to do the same thing instead of introducing a new "icon" key in this constant. If you want to keep the SVG files lowercase, you can use [to_lower()](https://docs.godotengine.org/en/stable/classes/class_string.html#class-string-method-to-lower)

2025-02-05 16:17 UTC, DoomTas3r commented
@manuq Alright, it's all cleaned up!

2025-02-06 01:45 UTC, manuq approved these changes

2025-02-06 01:46 UTC, merged